//! Offline integration generation. Frame policies are independent of hardware timing.
use std::{collections::HashSet, fmt::Write};

use serde::Deserialize;

use crate::{PortConfig, Profile, ProfileError, selection::validate_path};

const HEADER: &str = "# Generated by sidealsa-config-gen. Do not edit.\n\n";

#[derive(Clone, Debug, Default, Deserialize, PartialEq, Eq)]
#[serde(default, deny_unknown_fields)]
pub struct IntegrationConfig {
    pub pipewire: PipeWireConfig,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq)]
#[serde(default, deny_unknown_fields)]
pub struct PipeWireConfig {
    pub playback_headroom_frames: u32,
    pub capture_headroom_frames: u32,
    pub playback_start_delay_frames: u32,
}

impl Default for PipeWireConfig {
    fn default() -> Self {
        Self {
            playback_headroom_frames: 128,
            capture_headroom_frames: 0,
            playback_start_delay_frames: 256,
        }
    }
}

impl PipeWireConfig {
    pub(crate) fn validate(&self) -> Result<(), ProfileError> {
        for (name, value) in [
            ("playback_headroom_frames", self.playback_headroom_frames),
            ("capture_headroom_frames", self.capture_headroom_frames),
            (
                "playback_start_delay_frames",
                self.playback_start_delay_frames,
            ),
        ] {
            if value > i32::MAX as u32 {
                return Err(ProfileError::Invalid(format!("{name} must be <= i32::MAX")));
            }
        }
        Ok(())
    }
}

pub(crate) fn validate_positions(port: &PortConfig) -> Result<(), ProfileError> {
    let Some(positions) = &port.positions else {
        return Ok(());
    };
    let mut seen = HashSet::new();
    if positions.len() != port.channels.len()
        || positions.iter().any(|p| {
            let canonical = matches!(
                p.as_str(),
                "MONO"
                    | "FL"
                    | "FR"
                    | "FC"
                    | "LFE"
                    | "RL"
                    | "RR"
                    | "RC"
                    | "SL"
                    | "SR"
                    | "FLC"
                    | "FRC"
                    | "TC"
                    | "TFL"
                    | "TFC"
                    | "TFR"
                    | "TRL"
                    | "TRC"
                    | "TRR"
                    | "TFLC"
                    | "TFRC"
                    | "TSL"
                    | "TSR"
                    | "BC"
                    | "BLC"
                    | "BRC"
            ) || (0..64).any(|i| p == &format!("AUX{i}"));
            !canonical || !seen.insert(p) || (p == "MONO" && positions.len() != 1)
        })
    {
        return Err(ProfileError::Invalid(format!(
            "port '{}' has invalid positions (expected unique canonical SPA positions, one per channel; MONO alone)",
            port.id
        )));
    }
    Ok(())
}

fn positions(port: &PortConfig) -> Vec<String> {
    port.positions
        .clone()
        .unwrap_or_else(|| match port.channels.len() {
            1 => vec!["MONO".into()],
            2 => vec!["FL".into(), "FR".into()],
            count => (0..count).map(|i| format!("AUX{i}")).collect(),
        })
}

fn validate(profile: &Profile) -> Result<(), ProfileError> {
    profile.validate()?;
    if profile
        .ports
        .playback
        .iter()
        .chain(&profile.ports.capture)
        .any(|p| p.id == "pro")
    {
        return Err(ProfileError::Invalid(
            "port id 'pro' is reserved by the generator for sidealsa_pro".into(),
        ));
    }
    Ok(())
}

// Both ALSA and SPA quoted strings accept escaped quotes and backslashes.
fn quote(text: &str) -> String {
    format!("\"{}\"", text.replace('\\', "\\\\").replace('"', "\\\""))
}

pub fn render_alsa(profile: &Profile, socket: &str) -> Result<String, ProfileError> {
    validate(profile)?;
    validate_path(std::path::Path::new(socket))?;
    let socket = quote(socket);
    let mut out = format!(
        "{HEADER}pcm.sidealsa_pro {{\n    type sidealsa\n    mode pro\n    socket {socket}\n    hint {{\n        show on\n        description \"SideALSA PRO\"\n    }}\n}}\n"
    );
    for port in profile.ports.playback.iter().chain(&profile.ports.capture) {
        writeln!(out, "\npcm.sidealsa_{} {{\n    type sidealsa\n    mode shared\n    port {}\n    socket {socket}\n}}", port.id, quote(&port.id)).unwrap();
    }
    Ok(out)
}

pub fn render_pipewire(profile: &Profile) -> Result<String, ProfileError> {
    validate(profile)?;
    let policy = &profile.integration.pipewire;
    let mut out = format!(
        "{HEADER}module.rt.args = {{\n    nice.level       = -11\n    rt.prio          = 10\n    rtportal.enabled = false\n}}\n\ncontext.objects = [\n"
    );
    for (ports, playback) in [
        (&profile.ports.playback, true),
        (&profile.ports.capture, false),
    ] {
        for port in ports {
            if port.channels.len() > 64 {
                return Err(ProfileError::Invalid(format!(
                    "PipeWire port '{}' exceeds 64 logical channels",
                    port.id
                )));
            }
            let (factory, class, headroom) = if playback {
                ("sink", "Sink", policy.playback_headroom_frames)
            } else {
                ("source", "Source", policy.capture_headroom_frames)
            };
            writeln!(out, "    {{ factory = adapter\n        args = {{\n            factory.name         = api.alsa.pcm.{factory}\n            node.name            = {}\n            node.description     = {}\n            media.class          = \"Audio/{class}\"\n            api.alsa.path        = {}\n            api.alsa.headroom    = {headroom}", quote(&format!("sidealsa-{}", port.id)), quote(&format!("SideALSA {}", port.name)), quote(&format!("sidealsa_{}", port.id))).unwrap();
            if playback {
                writeln!(
                    out,
                    "            api.alsa.start-delay = {}",
                    policy.playback_start_delay_frames
                )
                .unwrap();
            }
            writeln!(out, "            api.alsa.disable-mmap = true\n            api.alsa.disable-batch = true\n            audio.channels       = {}\n            audio.position       = [ {} ]\n            node.suspend-on-idle = true\n        }}\n    }}", port.channels.len(), positions(port).join(" ")).unwrap();
        }
    }
    out.push_str("]\n");
    Ok(out)
}

pub fn compatible_topology(old: &Profile, new: &Profile) -> bool {
    if old.validate().is_err() || new.validate().is_err() {
        return false;
    }
    [
        (&old.ports.playback, &new.ports.playback),
        (&old.ports.capture, &new.ports.capture),
    ]
    .into_iter()
    .all(|(old, new)| {
        old.len() == new.len()
            && old.iter().all(|a| {
                new.iter().any(|b| {
                    a.id == b.id
                        && a.channels.len() == b.channels.len()
                        && positions(a) == positions(b)
                })
            })
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ProfileDocument;

    fn profile() -> Profile {
        Profile::from_toml(include_str!("../../../profiles/topping-e1x2.toml")).unwrap()
    }

    #[test]
    fn legacy_golden() {
        let profile = profile();
        assert_eq!(
            render_alsa(&profile, "/tmp/sidealsad.sock").unwrap(),
            format!(
                "{HEADER}{}",
                include_str!("../tests/fixtures/topping-asound.conf")
            )
        );
        let shipped = include_str!("../tests/fixtures/topping-pipewire.conf");
        let without_comments = |s: &str| {
            s.lines()
                .filter(|l| !l.trim().is_empty() && !l.starts_with('#'))
                .collect::<Vec<_>>()
                .join("\n")
        };
        assert_eq!(
            without_comments(&render_pipewire(&profile).unwrap()),
            without_comments(shipped)
        );
    }

    #[test]
    fn generic_channels_and_timing_independence() {
        let mut p = profile();
        let original = render_pipewire(&p).unwrap();
        p.device.rate = 44100;
        p.device.pro_handoff_us = 250;
        assert_eq!(render_pipewire(&p).unwrap(), original);
        p.ports.playback.truncate(1);
        p.ports.playback[0].channels = vec![0, 1, 2, 3];
        assert!(
            render_pipewire(&p)
                .unwrap()
                .contains("[ AUX0 AUX1 AUX2 AUX3 ]")
        );
        p.device.playback.channels = 65;
        p.ports.playback[0].channels = (0..65).collect();
        p.validate().unwrap();
        render_alsa(&p, "/tmp/socket").unwrap();
        assert!(render_pipewire(&p).is_err());
        p.ports.playback.clear();
        p.ports.capture.clear();
        assert!(
            render_pipewire(&p)
                .unwrap()
                .ends_with("context.objects = [\n]\n")
        );
        assert_eq!(
            render_alsa(&p, "/tmp/socket")
                .unwrap()
                .matches("pcm.")
                .count(),
            1
        );
    }

    #[test]
    fn escaping_and_reserved_id() {
        let mut p = profile();
        p.ports.playback[0].name = "quote\" slash\\ # {}".into();
        assert!(
            render_pipewire(&p)
                .unwrap()
                .contains("\"SideALSA quote\\\" slash\\\\ # {}\"")
        );
        assert!(
            render_alsa(&p, "/tmp/a\"b\\c")
                .unwrap()
                .contains("socket \"/tmp/a\\\"b\\\\c\"")
        );
        for socket in ["relative", "/tmp/a\n", "/tmp/\0"] {
            assert!(render_alsa(&p, socket).is_err());
        }
        p.ports.playback[0].id = "pro".into();
        p.validate().unwrap();
        assert!(render_alsa(&p, "/tmp/socket").is_err());
        assert!(render_pipewire(&p).is_err());
    }

    #[test]
    fn validates_positions_and_policies() {
        let mut p = profile();
        for invalid in [
            vec!["FL"],
            vec!["FL", "FL"],
            vec!["MONO", "FR"],
            vec!["AUX64", "FR"],
            vec!["AUX01", "FR"],
            vec!["fl", "FR"],
            vec!["FL\"", "FR"],
        ] {
            p.ports.playback[0].positions = Some(invalid.into_iter().map(str::to_owned).collect());
            assert!(p.validate().is_err());
        }
        for valid in [["TFL", "TFR"], ["AUX0", "AUX63"], ["SL", "SR"]] {
            p.ports.playback[0].positions = Some(valid.into_iter().map(str::to_owned).collect());
            p.validate().unwrap();
        }
        for field in 0..3 {
            p.integration.pipewire = PipeWireConfig::default();
            let policy = &mut p.integration.pipewire;
            let value = match field {
                0 => &mut policy.playback_headroom_frames,
                1 => &mut policy.capture_headroom_frames,
                _ => &mut policy.playback_start_delay_frames,
            };
            *value = i32::MAX as u32 + 1;
            assert!(p.validate().is_err());
        }
    }

    #[test]
    fn topology_ignores_order_names_mapping_timing_and_policy() {
        let old = profile();
        let mut new = old.clone();
        new.ports.playback.reverse();
        new.ports.playback[0].name = "Renamed".into();
        new.ports.playback[0].channels.reverse();
        new.ports.playback[0].positions = Some(vec!["FL".into(), "FR".into()]);
        new.integration.pipewire.playback_headroom_frames = 42;
        new.device.rate = 44100;
        assert!(compatible_topology(&old, &new));
        new.ports.playback[0].positions = Some(vec!["FR".into(), "FL".into()]);
        assert!(!compatible_topology(&old, &new));
        let mut new = old.clone();
        new.ports.playback[0].id = "changed".into();
        assert!(!compatible_topology(&old, &new));
        let mut new = old.clone();
        new.ports.playback[0].channels.pop();
        assert!(!compatible_topology(&old, &new));
        let mut new = old.clone();
        new.ports.capture.clear();
        new.ports.capture.push(new.ports.playback.remove(0));
        assert!(!compatible_topology(&old, &new));
    }

    #[test]
    fn metadata_survives_timing_edits_and_extends_fingerprint() {
        let text = include_str!("../../../profiles/topping-e1x2.toml");
        let baseline = profile();
        // Reconstruct the pre-metadata hash to guard shipped fingerprint compatibility.
        let mut legacy = 0xcbf29ce484222325;
        crate::hash_u64(
            &mut legacy,
            crate::TimingSettings::from(&baseline.device).fingerprint(),
        );
        crate::hash_string(&mut legacy, &baseline.device.name);
        crate::hash_pcm(&mut legacy, &baseline.device.playback);
        crate::hash_pcm(&mut legacy, &baseline.device.capture);
        crate::hash_ports(&mut legacy, &baseline.ports.playback);
        crate::hash_ports(&mut legacy, &baseline.ports.capture);
        assert_eq!(legacy, baseline.fingerprint());
        let defaults = format!(
            "{text}\n[integration.pipewire]\nplayback_headroom_frames = 128\ncapture_headroom_frames = 0\nplayback_start_delay_frames = 256\n"
        );
        assert_eq!(Profile::from_toml(&defaults).unwrap().fingerprint(), legacy);
        let explicit = text.replacen(
            "channels = [0, 1]",
            "channels = [0, 1]\npositions = [\"FL\", \"FR\"]",
            1,
        );
        assert_ne!(Profile::from_toml(&explicit).unwrap().fingerprint(), legacy);
        let text = format!("{explicit}\n[integration.pipewire]\nplayback_headroom_frames = 99\n");
        let mut document = ProfileDocument::from_toml(&text).unwrap();
        let metadata = document.profile().integration.clone();
        let ports = document.profile().ports.clone();
        let mut timing = document.timing();
        timing.shared_latency_periods = 6;
        document.apply_timing(&timing).unwrap();
        assert_eq!(document.profile().integration, metadata);
        assert_eq!(document.profile().ports, ports);
        let mut changed = baseline.clone();
        changed.integration.pipewire.capture_headroom_frames = 1;
        assert_ne!(changed.fingerprint(), legacy);
    }
}
