pcm.sidealsa_pro {
    type sidealsa
    mode pro
    socket "/tmp/sidealsad.sock"
    hint {
        show on
        description "SideALSA PRO"
    }
}

pcm.sidealsa_line1 {
    type sidealsa
    mode shared
    port "line1"
    socket "/tmp/sidealsad.sock"
}

pcm.sidealsa_line2 {
    type sidealsa
    mode shared
    port "line2"
    socket "/tmp/sidealsad.sock"
}

pcm.sidealsa_line3 {
    type sidealsa
    mode shared
    port "line3"
    socket "/tmp/sidealsad.sock"
}

pcm.sidealsa_line4 {
    type sidealsa
    mode shared
    port "line4"
    socket "/tmp/sidealsad.sock"
}

pcm.sidealsa_mic1 {
    type sidealsa
    mode shared
    port "mic1"
    socket "/tmp/sidealsad.sock"
}

pcm.sidealsa_mic2 {
    type sidealsa
    mode shared
    port "mic2"
    socket "/tmp/sidealsad.sock"
}

pcm.sidealsa_input34 {
    type sidealsa
    mode shared
    port "input34"
    socket "/tmp/sidealsad.sock"
}

pcm.sidealsa_input56 {
    type sidealsa
    mode shared
    port "input56"
    socket "/tmp/sidealsad.sock"
}

pcm.sidealsa_input78 {
    type sidealsa
    mode shared
    port "input78"
    socket "/tmp/sidealsad.sock"
}

pcm.sidealsa_input910 {
    type sidealsa
    mode shared
    port "input910"
    socket "/tmp/sidealsad.sock"
}
